# Generated by Django 6.1.1 on 2026-09-10 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Title"),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, default="", verbose_name="Body"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Info"),
                            (2, "Success"),
                            (3, "Warning"),
                            (4, "Critical"),
                        ],
                        db_index=True,
                        default=1,
                        verbose_name="Level",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where clicking the notification leads.",
                        max_length=500,
                        verbose_name="Link",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Object id"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Read at",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Model",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Recipient of this notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="generic_notif_user_read_idx",
                    )
                ],
            },
        ),
    ]
