# Generated by Django 6.1.1 on 2026-09-11 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("generic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("system", "Follow the system"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="system",
                        max_length=10,
                        verbose_name="theme",
                    ),
                ),
                (
                    "table_page_size",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (10, "10"),
                            (15, "15"),
                            (25, "25"),
                            (50, "50"),
                            (100, "100"),
                        ],
                        help_text="How many rows a table shows at first. Leave empty to use each table's own default.",
                        null=True,
                        verbose_name="rows per page",
                    ),
                ),
                (
                    "remember_table_state",
                    models.BooleanField(
                        default=True,
                        help_text="A table comes back with the filters, columns and sorting you left it with.",
                        verbose_name="remember table layouts",
                    ),
                ),
                (
                    "notification_channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In the application"),
                            ("email", "By e-mail"),
                            ("both", "Both"),
                        ],
                        default="in_app",
                        help_text="How you want to hear about what needs you.",
                        max_length=10,
                        verbose_name="notifications",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generic_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "preferences",
                "verbose_name_plural": "preferences",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=64, verbose_name="object id"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="label"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="created at",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="model",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generic_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "favorite",
                "verbose_name_plural": "favorites",
                "ordering": ("-created_at", "-pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "content_type", "object_id"),
                        name="generic_favorite_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="table"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "state",
                    models.JSONField(default=dict, verbose_name="state"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Applied when the table opens.",
                        verbose_name="default",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generic_saved_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "saved view",
                "verbose_name_plural": "saved views",
                "ordering": ("name", "pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "table", "name"),
                        name="generic_saved_view_unique",
                    )
                ],
            },
        ),
    ]
