# Generated by Django 6.1.1 on 2026-09-11 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0002_userpreferences_favorite_savedview"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="accent_hue",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Hue of the accent, in degrees.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(360)],
                verbose_name="accent colour",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="colorfulness",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="0 for greys only, 100 for the standard colours.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(130)],
                verbose_name="colourfulness",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="contrast",
            field=models.SmallIntegerField(
                blank=True,
                help_text="From -100, soft, to 100, strong.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="contrast",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="stripes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How visible every other table row is.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="table stripes",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="tint",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How much of the accent the backgrounds carry.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="tint of the greys",
            ),
        ),
    ]
