# Generated by Django 6.1.1 on 2026-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0003_userpreferences_appearance"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Leave empty to follow the browser's language.",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
