# Generated by Django 6.1.1 on 2026-09-18 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0004_userpreferences_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RestartAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="When the server goes down, in your own time zone.",
                        verbose_name="restart at",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="How long it is expected to be unavailable, in minutes.",
                        verbose_name="estimated duration",
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=True,
                        help_text="Tick it when you restart the server yourself: the application only warns people. Untick it and the server restarts itself at the hour announced.",
                        verbose_name="manual operation",
                    ),
                ),
                (
                    "comment_en",
                    models.TextField(
                        default="The application will be unavailable for a few minutes while the server restarts. Finish what you are doing and save your work.",
                        help_text="Shown to everyone reading the application in English.",
                        verbose_name="comment (English)",
                    ),
                ),
                (
                    "comment_fr",
                    models.TextField(
                        default="L'application sera indisponible quelques minutes, le temps du redémarrage du serveur. Terminez ce que vous faites et enregistrez votre travail.",
                        help_text="Shown to everyone reading the application in French.",
                        verbose_name="comment (French)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="announced at",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "restarted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="restarted at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generic_restart_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="announced by",
                    ),
                ),
            ],
            options={
                "verbose_name": "restart announcement",
                "verbose_name_plural": "restart announcements",
                "ordering": ("-scheduled_at", "-pk"),
            },
        ),
    ]
