# Generated by Django 6.1.1 on 2026-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0005_restartannouncement"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="skin",
            field=models.CharField(
                choices=[("generic", "Generic"), ("admin", "Django admin")],
                default="generic",
                max_length=10,
                verbose_name="interface style",
            ),
        ),
    ]
