# Generated by Django 6.1.1 on 2026-09-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0006_userpreferences_skin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="skin",
        ),
    ]
