# Generated by Django 6.1.1 on 2026-09-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0007_remove_userpreferences_skin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="navigation",
            field=models.CharField(
                choices=[
                    ("pinned", "Pinned beside the page"),
                    ("floating", "Floating over the page"),
                ],
                default="pinned",
                help_text=(
                    "Pinned, the navigation holds the page open beside "
                    "it. Floating, the page takes the whole width and "
                    "the navigation slides out from the left edge."
                ),
                max_length=10,
                verbose_name="navigation",
            ),
        ),
    ]
