# Generated by Django 6.1.1 on 2026-09-19 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0008_userpreferences_navigation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        db_index=True,
                        help_text="The declared name the schedule and Celery both use.",
                        max_length=200,
                        verbose_name="task",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="label"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting"),
                            ("running", "Running"),
                            ("success", "Finished"),
                            ("failure", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "By hand"),
                            ("schedule", "On schedule"),
                            ("code", "By the application"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="started",
                    ),
                ),
                (
                    "arguments",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="arguments"
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="queued at",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="summary"
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True, default=list, verbose_name="results"
                    ),
                ),
                (
                    "log",
                    models.JSONField(
                        blank=True, default=list, verbose_name="steps"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="error")),
                (
                    "celery_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Celery id"
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generic_task_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="started by",
                    ),
                ),
            ],
            options={
                "verbose_name": "task run",
                "verbose_name_plural": "task runs",
                "ordering": ("-queued_at", "-pk"),
                "permissions": (("run_task", "Can run a task by hand"),),
                "indexes": [
                    models.Index(
                        fields=["task", "-queued_at"],
                        name="generic_run_task_idx",
                    )
                ],
            },
        ),
    ]
