# Generated by Django 6.1.1 on 2026-09-19 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0009_taskrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="interface_scale",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    "Everything on the page, as a percentage. Raise it "
                    "on a screen that scales badly, lower it to fit "
                    "more in."
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(75),
                    django.core.validators.MaxValueValidator(150),
                ],
                verbose_name="interface size",
            ),
        ),
    ]
