# Generated by Django 6.1.1 on 2026-09-19 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("generic", "0010_userpreferences_interface_scale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Empty to watch every record of the model.",
                        max_length=64,
                        verbose_name="record",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="label"
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Which changes are worth a message.",
                        verbose_name="changes",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Empty to follow the choice made in your preferences.",
                        verbose_name="how",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="watched since",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="model",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generic_watches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "watch",
                "verbose_name_plural": "watches",
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="generic_watch_target_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "content_type", "object_id"),
                        name="generic_watch_once_each",
                    )
                ],
            },
        ),
    ]
