# Generated by Django 6.1.1 on 2026-09-21 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("generic", "0011_watch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=64, verbose_name="record"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="record"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, verbose_name="version"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Changed"),
                            ("deleted", "Deleted"),
                        ],
                        default="updated",
                        max_length=10,
                        verbose_name="change",
                    ),
                ),
                (
                    "user_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="by"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="source"
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="when"
                    ),
                ),
                (
                    "batch",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "values",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="values"
                    ),
                ),
            ],
            options={
                "verbose_name": "history entry",
                "verbose_name_plural": "history",
                "ordering": ("-at", "-pk"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="favorite",
            name="generic_favorite_unique",
        ),
        migrations.AddField(
            model_name="historyentry",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="model",
            ),
        ),
        migrations.AddField(
            model_name="historyentry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generic_history_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="by",
            ),
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="user",
        ),
        migrations.AddIndex(
            model_name="historyentry",
            index=models.Index(
                fields=["content_type", "object_id", "-version"],
                name="generic_history_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historyentry",
            index=models.Index(fields=["-at"], name="generic_history_at_idx"),
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
