# Generated by Django 5.2.17 on 2026-09-26 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("generic", "0014_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The subject of every e-mail.",
                        max_length=120,
                        verbose_name="name",
                    ),
                ),
                (
                    "table",
                    models.CharField(
                        db_index=True,
                        help_text="The list it sends, as the site names it.",
                        max_length=150,
                        verbose_name="table",
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Columns, order, filters and search of the list.",
                        verbose_name="layout",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("xlsx", "Excel"), ("csv", "CSV")],
                        default="xlsx",
                        max_length=4,
                        verbose_name="format",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Every day"),
                            ("weekdays", "Every weekday"),
                            ("weekly", "Every week"),
                            ("monthly", "Every month"),
                        ],
                        default="weekdays",
                        max_length=10,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        default="08:00",
                        help_text="In the application's time zone.",
                        verbose_name="time",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                        help_text="For a weekly mailing.",
                        verbose_name="day of the week",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="For a monthly mailing: 1 to 28, so every month has it.",
                        verbose_name="day of the month",
                    ),
                ),
                (
                    "include_owner",
                    models.BooleanField(
                        default=True, verbose_name="send it to me"
                    ),
                ),
                (
                    "send_when_empty",
                    models.BooleanField(
                        default=False,
                        help_text="Otherwise a list with no rows is not sent.",
                        verbose_name="send when empty",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="next sending",
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="last sent",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="last problem",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Every active member of these groups.",
                        related_name="+",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generic_mailings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="people",
                    ),
                ),
            ],
            options={
                "verbose_name": "scheduled mailing",
                "verbose_name_plural": "scheduled mailings",
                "ordering": ("name", "pk"),
            },
        ),
    ]
