# Generated by Django 5.2.17 on 2026-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0015_scheduledmailing"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrun",
            name="language",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="language"
            ),
        ),
        migrations.AddField(
            model_name="taskrun",
            name="tree",
            field=models.JSONField(
                blank=True, default=list, verbose_name="report"
            ),
        ),
    ]
