# Generated by Django 5.2.17 on 2026-10-03 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0016_taskrun_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="series"
                    ),
                ),
                (
                    "value",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="last number"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "number sequence",
                "verbose_name_plural": "number sequences",
                "ordering": ("key",),
            },
        ),
    ]
