# Generated by Django 5.2.17 on 2026-10-03 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("generic", "0017_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=64, verbose_name="record"),
                ),
                (
                    "record_key",
                    models.CharField(
                        db_index=True,
                        max_length=120,
                        verbose_name="record key",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="record"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("viewed", "Opened"),
                            ("downloaded", "Downloaded"),
                        ],
                        default="viewed",
                        max_length=12,
                        verbose_name="access",
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="detail"
                    ),
                ),
                (
                    "user_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="by"
                    ),
                ),
                (
                    "address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="address"
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="when"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="model",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generic_access_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="by",
                    ),
                ),
            ],
            options={
                "verbose_name": "access",
                "verbose_name_plural": "access log",
                "ordering": ("-at", "-pk"),
                "indexes": [
                    models.Index(fields=["-at"], name="generic_access_at_idx")
                ],
            },
        ),
    ]
