# Generated by Django 6.1.1 on 2026-09-10 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="code"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
            ],
            options={
                "verbose_name": "team",
                "verbose_name_plural": "teams",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "hired_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="hired on"
                    ),
                ),
                (
                    "capacity_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=35,
                        help_text="Hours available per week.",
                        max_digits=5,
                        verbose_name="weekly capacity",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="example.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "agent",
                "verbose_name_plural": "agents",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="reference"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=False, verbose_name="billable"
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="estimated hours",
                    ),
                ),
                (
                    "satisfaction",
                    models.FloatField(
                        blank=True,
                        help_text="Score out of 5, once the ticket is closed.",
                        null=True,
                        verbose_name="satisfaction",
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="opened at",
                    ),
                ),
                (
                    "due_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="due on"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="example.agent",
                        verbose_name="assignee",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tickets",
                        to="example.tag",
                        verbose_name="tags",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="example.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket",
                "verbose_name_plural": "tickets",
                "ordering": ("-opened_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=80, verbose_name="author"),
                ),
                ("body", models.TextField(verbose_name="comment")),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="order"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="created at",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="example.ticket",
                        verbose_name="ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ("position", "pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "position"),
                        name="example_comment_unique_position",
                    )
                ],
            },
        ),
    ]
