# Generated by Django 6.1.1 on 2026-09-11 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="code"
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("enterprise", "Enterprise"),
                            ("small", "Small business"),
                            ("public", "Public sector"),
                        ],
                        default="small",
                        max_length=12,
                        verbose_name="segment",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="city",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, default="", verbose_name="website"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "customer_since",
                    models.DateField(
                        blank=True, null=True, verbose_name="customer since"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="notes"
                    ),
                ),
                (
                    "account_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="example.agent",
                        verbose_name="account manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="example.customer",
                verbose_name="customer",
            ),
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spent_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="hours"
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(default=True, verbose_name="billable"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="note",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="example.agent",
                        verbose_name="agent",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="example.ticket",
                        verbose_name="ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "time entry",
                "verbose_name_plural": "time entries",
                "ordering": ("-spent_on", "-pk"),
            },
        ),
    ]
