# Generated by Django 6.1.1 on 2026-09-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_customer_timeentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="background",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Draws the tag on this colour, the text in 'colour'.",
                max_length=30,
                verbose_name="background",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Alone, the colour the tag is tinted with.",
                max_length=30,
                verbose_name="colour",
            ),
        ),
    ]
