# Generated by Django 6.1.1 on 2026-09-25 09:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0003_tag_colors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="phone",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, default="", verbose_name="website"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="country",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False, verbose_name="preferred"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="notes"
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="name"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=60,
                        unique=True,
                        verbose_name="serial number",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("laptop", "Laptop"),
                            ("screen", "Screen"),
                            ("phone", "Phone"),
                            ("headset", "Headset"),
                            ("other", "Other"),
                        ],
                        default="laptop",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("in_use", "In use"),
                            ("spare", "Spare"),
                            ("repair", "Being repaired"),
                            ("retired", "Retired"),
                        ],
                        default="spare",
                        max_length=10,
                        verbose_name="state",
                    ),
                ),
                (
                    "purchased_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="purchased on"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="price",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="notes"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="example.agent",
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment",
                        to="example.supplier",
                        verbose_name="supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipment",
                "verbose_name_plural": "equipment",
                "ordering": ("name", "serial_number"),
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performed_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="performed on",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="description"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="cost",
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="done"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="example.equipment",
                        verbose_name="equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "maintenance visit",
                "verbose_name_plural": "maintenance visits",
                "ordering": ("-performed_on", "-pk"),
            },
        ),
    ]
