# Generated by Django 5.2.17 on 2026-09-26 17:26

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0005_search_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ("-opened_at", "-pk"),
                "permissions": [("reopen_ticket", "Can reopen a ticket")],
                "verbose_name": "ticket",
                "verbose_name_plural": "tickets",
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolution",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What was done, written when the ticket is resolved.",
                verbose_name="resolution",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("open", "Open"),
                    ("pending", "Pending"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
