# Generated by Django 5.2.17 on 2026-09-27 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0006_ticket_life"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                upload_to="tickets/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "png", "jpg", "jpeg", "txt", "csv", "xlsx"]
                    )
                ],
                verbose_name="attachment",
            ),
        ),
    ]
