# Generated by Django 5.2.17 on 2026-10-02 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0007_ticket_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                upload_to="tickets/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "png",
                            "jpg",
                            "jpeg",
                            "txt",
                            "csv",
                            "xlsx",
                            "docx",
                        ]
                    )
                ],
                verbose_name="attachment",
            ),
        ),
    ]
