# Generated by Django 6.1.2 on 2026-10-06 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0007_ticket_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="example.articlefamily",
                        verbose_name="parent family",
                    ),
                ),
            ],
            options={
                "verbose_name": "article family",
                "verbose_name_plural": "article families",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="reference"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="name"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("assembly", "Assembly"),
                            ("part", "Part"),
                            ("material", "Raw material"),
                        ],
                        default="part",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "piece"),
                            ("m", "metre"),
                            ("kg", "kilogram"),
                            ("l", "litre"),
                        ],
                        default="pcs",
                        max_length=3,
                        verbose_name="unit",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="unit cost",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="example.articlefamily",
                        verbose_name="family",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ("reference",),
            },
        ),
        migrations.CreateModel(
            name="BomLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=10, verbose_name="position"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=10,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="note",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_lines",
                        to="example.article",
                        verbose_name="component",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lines",
                        to="example.article",
                        verbose_name="assembly",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM line",
                "verbose_name_plural": "BOM lines",
                "ordering": ("parent", "position", "pk"),
            },
        ),
    ]
