# Generated by Django 5.2.17 on 2026-10-03 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="leaders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Team leaders: they see its records too.",
                related_name="generic_led_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="leaders",
            ),
        ),
    ]
