# Generated by Django 5.2.17 on 2026-09-26 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "digest",
                    models.CharField(
                        max_length=128, primary_key=True, serialize=False
                    ),
                ),
                ("token_key", models.CharField(db_index=True, max_length=25)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="What uses it: a script, a report, a colleague's tool.",
                        max_length=80,
                        verbose_name="name",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("read", "Read only"),
                            ("read_write", "Read and write"),
                        ],
                        default="read",
                        max_length=12,
                        verbose_name="scope",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="last used",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "API token",
                "verbose_name_plural": "API tokens",
                "ordering": ("name", "created"),
            },
        ),
    ]
