"""Serializers that also describe their table."""

from __future__ import annotations

from typing import Any

from rest_framework import serializers

from generic.api.columns import (
    ColumnOptions,
    DataTableFieldMixin,
    FilterSpec,
    iter_datatable_fields,
)


class DataTableSerializerMixin:
    """Expose the DataTables configuration carried by the fields.

    A subclass may adjust inherited columns without redeclaring them::

        class TimeTrackingSerializer(SubtasksSerializer):
            datatable_overrides = {
                "colonne": {"visible": False},
            }

    Overrides merge along the MRO, so a subclass only states what it
    changes. Unknown option names raise ``TypeError`` at build time.
    """

    datatable_overrides: dict[str, dict[str, Any]] = {}

    @classmethod
    def get_merged_datatable_overrides(
        cls,
    ) -> dict[str, dict[str, Any]]:
        merged: dict[str, dict[str, Any]] = {}

        for klass in reversed(cls.__mro__):  # type: ignore[attr-defined]
            declared = vars(klass).get("datatable_overrides", {})

            for field_name, overrides in declared.items():
                merged.setdefault(field_name, {}).update(overrides)

        return merged

    @classmethod
    def get_datatable_fields(
        cls,
    ) -> list[tuple[str, DataTableFieldMixin, ColumnOptions]]:
        """Bound table aware fields, in display order.

        The serializer is instantiated rather than read from
        ``_declared_fields`` so that fields generated by
        ``ModelSerializer`` are visible too, and so that every field
        carries the label DRF derives from its name.
        """
        serializer = cls()  # type: ignore[call-arg]

        return iter_datatable_fields(
            serializer.fields.items(),
            cls.get_merged_datatable_overrides(),
        )

    @classmethod
    def get_datatable_columns(cls) -> list[dict[str, Any]]:
        """JSON column configuration handed to the client."""
        return [
            field.build_column(field_name, options)
            for field_name, field, options in cls.get_datatable_fields()
        ]

    @classmethod
    def get_filter_specs(cls) -> dict[str, FilterSpec]:
        """Public column name -> how it may be filtered.

        This is the whitelist: a name absent from it cannot be filtered,
        whatever the client sends.
        """
        return {
            field_name: field.build_filter(field_name, options)
            for field_name, field, options in cls.get_datatable_fields()
            if options.filterable
        }

    @classmethod
    def get_ordering_fields(cls) -> dict[str, str]:
        """Public column name -> ORM path allowed for ordering."""
        return {
            field_name: options.order_field or field_name
            for field_name, _, options in cls.get_datatable_fields()
            if options.orderable
        }

    @classmethod
    def get_search_fields(cls) -> list[str]:
        """ORM paths the global search box spans."""
        paths = [
            field.build_search_field(field_name, options)
            for field_name, field, options in cls.get_datatable_fields()
        ]

        # Preserve order, drop duplicates and opted out columns.
        return list(dict.fromkeys(path for path in paths if path))

    @classmethod
    def get_export_columns(cls) -> list[dict[str, Any]]:
        """Columns eligible for an export, in display order."""
        return [
            field.build_column(field_name, options)
            for field_name, field, options in cls.get_datatable_fields()
            if options.exportable
        ]


class DataTableSerializer(
    DataTableSerializerMixin,
    serializers.Serializer,
):
    """Plain serializer over ``values()`` rows.

    Used by read only tables built from an aggregated queryset, where
    there is no single model behind a row.
    """


class DataTableModelSerializer(
    DataTableSerializerMixin,
    serializers.ModelSerializer,
):
    """Model backed table.

    Fields not declared as columns still serialize normally; they simply
    do not appear in the table configuration.
    """
