# Generated by Django 5.2.17 on 2026-10-02 21:43

from pathlib import PurePosixPath

from django.db import migrations, models


def extension_of(name):
    return PurePosixPath(name or "").suffix.lstrip(".").upper()[:10]


def fill_formats(apps, schema_editor):
    """Documents and versions sent before formats were kept."""
    Document = apps.get_model("documents", "Document")
    DocumentVersion = apps.get_model("documents", "DocumentVersion")

    for document in Document.objects.all().iterator():
        Document.objects.filter(pk=document.pk).update(
            file_format=extension_of(document.file.name)
        )

    for version in DocumentVersion.objects.all().iterator():
        DocumentVersion.objects.filter(pk=version.pk).update(
            file_format=extension_of(version.file_name or version.file.name)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_format",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=10,
                verbose_name="format",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="file_format",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=10,
                verbose_name="format",
            ),
        ),
        migrations.RunPython(fill_formats, migrations.RunPython.noop),
    ]
