# Generated by Django 5.2.17 on 2026-10-03 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_file_format"),
        ("generic_teams", "0001_initial"),
        ("generic_wiki", "0006_wiki_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamWiki",
            fields=[
                (
                    "wiki",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="team_link",
                        serialize=False,
                        to="generic_wiki.wiki",
                        verbose_name="wiki",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wikis",
                        to="generic_teams.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "team wiki",
                "verbose_name_plural": "team wikis",
                "ordering": ("team__name", "wiki__name"),
            },
        ),
    ]
