# Generated by Django 5.2.17 on 2026-10-03 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("documents", "0003_team_wiki"),
        ("generic_teams", "0002_leaders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Codification",
            fields=[
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="codification",
                        serialize=False,
                        to="generic_teams.team",
                        verbose_name="team",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short, in the numbers ({team}): LEG, ENG...",
                        max_length=10,
                        verbose_name="team code",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        default="{team}-{type}-{year}-{seq:04}",
                        help_text="{team}, {type}, {year}, {yy}, {month}, {day} and the running number {seq} - {seq:04} pads it to four digits. Each series counts on its own: with {year}, from 1 again every year.",
                        max_length=120,
                        validators=[documents.models.validate_pattern],
                        verbose_name="pattern",
                    ),
                ),
                (
                    "on_create",
                    models.BooleanField(
                        default=False,
                        help_text="Otherwise a document is numbered when asked (Codify).",
                        verbose_name="number every new document",
                    ),
                ),
            ],
            options={
                "verbose_name": "codification",
                "verbose_name_plural": "codifications",
                "ordering": ("team__name",),
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short, in the numbers: CTR, PRC...",
                        max_length=10,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="colour"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
            ],
            options={
                "verbose_name": "document type",
                "verbose_name_plural": "document types",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="teamwiki",
            options={
                "ordering": ("wiki__position", "wiki__name"),
                "verbose_name": "team wiki",
                "verbose_name_plural": "team wikis",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="checked_out_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="checked out at",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="checked_out_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="checked out by",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=60,
                null=True,
                unique=True,
                verbose_name="number",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="codified_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="numbered at",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="related",
            field=models.ManyToManyField(
                blank=True,
                to="documents.document",
                verbose_name="related documents",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="review_on",
            field=models.DateField(
                blank=True,
                help_text="When the document should be read again.",
                null=True,
                verbose_name="next review on",
            ),
        ),
        migrations.AddField(
            model_name="teamwiki",
            name="editing_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="The teams writing in it - they read it too. None: whoever reads it writes in it, with the page permissions.",
                related_name="edited_wikis",
                to="generic_teams.team",
                verbose_name="editing teams",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                upload_to=documents.models.file_path,
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="teamwiki",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="The team reading it; empty, everyone reads it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wikis",
                to="generic_teams.team",
                verbose_name="readers",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="comment")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="written at",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="documents.documenttype",
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What the reviewers should know - sent with the task.",
                        verbose_name="message",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Preparing"),
                            ("in_progress", "In progress"),
                            ("approved", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="preparing",
                        editable=False,
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="version"
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        verbose_name="status before",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="started at",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="finished at",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="started by",
                    ),
                ),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="ReviewStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_leaders",
                    models.BooleanField(
                        default=False,
                        help_text="Those leading the document's team.",
                        verbose_name="the team's leaders",
                    ),
                ),
                (
                    "team_members",
                    models.BooleanField(
                        default=False,
                        help_text="Everyone in the document's team.",
                        verbose_name="the team's members",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=1, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="name"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("approval", "Approval"),
                            ("acknowledgement", "Acknowledgement"),
                        ],
                        default="approval",
                        max_length=20,
                        verbose_name="asks to",
                    ),
                ),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            ("any", "One of them"),
                            ("all", "Each of them"),
                        ],
                        default="any",
                        help_text="One of them: the first answer closes the step. Each of them: everyone answers.",
                        max_length=10,
                        verbose_name="answered by",
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="A due date, for the reminders; never a deadline.",
                        null=True,
                        verbose_name="days to answer",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "In progress"),
                            ("done", "Done"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                        ],
                        default="waiting",
                        editable=False,
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "due_on",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="due on",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="started at",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="finished at",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Every active member of these groups.",
                        related_name="+",
                        to="auth.group",
                        verbose_name="roles",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="documents.review",
                        verbose_name="review",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="people",
                    ),
                ),
            ],
            options={
                "verbose_name": "review step",
                "verbose_name_plural": "review steps",
                "ordering": ("review", "position", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "To do"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("delegated", "Delegated"),
                            ("skipped", "Not needed"),
                        ],
                        default="pending",
                        editable=False,
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="comment"
                    ),
                ),
                (
                    "due_on",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="due on",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="asked at",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="answered at",
                    ),
                ),
                (
                    "reminded_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="reminded at",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="asked of",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="answered by",
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="delegated to",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="documents.review",
                        verbose_name="review",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="documents.reviewstep",
                        verbose_name="step",
                    ),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop offering it; reviews keep going.",
                        verbose_name="offered",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Offered to this team only; empty, to everyone.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="generic_teams.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow",
                "verbose_name_plural": "workflows",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="review",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="Its steps are copied into the review, where they may still be changed. Empty: draw the steps below.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="documents.workflow",
                verbose_name="workflow",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_leaders",
                    models.BooleanField(
                        default=False,
                        help_text="Those leading the document's team.",
                        verbose_name="the team's leaders",
                    ),
                ),
                (
                    "team_members",
                    models.BooleanField(
                        default=False,
                        help_text="Everyone in the document's team.",
                        verbose_name="the team's members",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=1, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="name"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("approval", "Approval"),
                            ("acknowledgement", "Acknowledgement"),
                        ],
                        default="approval",
                        max_length=20,
                        verbose_name="asks to",
                    ),
                ),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            ("any", "One of them"),
                            ("all", "Each of them"),
                        ],
                        default="any",
                        help_text="One of them: the first answer closes the step. Each of them: everyone answers.",
                        max_length=10,
                        verbose_name="answered by",
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="A due date, for the reminders; never a deadline.",
                        null=True,
                        verbose_name="days to answer",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Every active member of these groups.",
                        related_name="+",
                        to="auth.group",
                        verbose_name="roles",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="people",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="documents.workflow",
                        verbose_name="workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "step",
                "verbose_name_plural": "steps",
                "ordering": ("workflow", "position", "pk"),
            },
        ),
    ]
