# Generated by Django 5.2.17 on 2026-10-03 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import documents.models


def fill(apps, schema_editor):
    """Paths for the folders already there, labels for the versions:
    drafts 0.1, 0.2...; an approved document's latest version, 1.0 -
    published."""
    Folder = apps.get_model("documents", "Folder")
    Document = apps.get_model("documents", "Document")

    for folder in Folder.objects.filter(path=""):
        folder.path = folder.name
        folder.save(update_fields=("path",))

    for document in Document.objects.all():
        versions = list(document.versions.order_by("number"))

        for minor, version in enumerate(versions, start=1):
            version.label = f"0.{minor}"

        latest = versions[-1] if versions else None

        if latest is not None and document.status == "approved":
            latest.label = "1.0"
            latest.published_at = latest.created_at
            document.published_version = latest
            document.published_file = latest.file.name
            document.published_label = latest.label
            document.published_at = latest.created_at

        for version in versions:
            version.save(update_fields=("label", "published_at"))

        document.version_label = latest.label if latest else ""
        document.save(
            update_fields=(
                "version_label",
                "published_version",
                "published_file",
                "published_label",
                "published_at",
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_ged"),
        ("generic_teams", "0002_leaders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="folder",
            options={
                "ordering": ("team__name", "path"),
                "verbose_name": "folder",
                "verbose_name_plural": "folders",
            },
        ),
        migrations.RemoveConstraint(
            model_name="folder",
            name="documents_folder_unique_name",
        ),
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.TextField(
                blank=True, default="", editable=False, verbose_name="text"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="deleted at",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="deleted by",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="published at",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="published_file",
            field=models.FileField(
                blank=True,
                editable=False,
                max_length=255,
                upload_to="",
                verbose_name="published file",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="published_label",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=12,
                verbose_name="published version",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="published_version",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.documentversion",
                verbose_name="published version",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="review_notice_for",
            field=models.DateField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="reminded of the review on",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="version_label",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=12,
                verbose_name="version",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="review_months",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Once approved, a document's next review is set this many months ahead. Empty: no periodic review.",
                null=True,
                verbose_name="reviewed every (months)",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="review_workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="Started on its own when a document is due for its review. Empty: its author and team leaders are only reminded.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.workflow",
                verbose_name="periodic review workflow",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="content",
            field=models.TextField(
                blank=True, default="", editable=False, verbose_name="text"
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="label",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=12,
                verbose_name="version",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="published at",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="published by",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="stamped",
            field=models.FileField(
                blank=True,
                editable=False,
                max_length=255,
                upload_to=documents.models.file_path,
                verbose_name="stamped copy",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Empty: at the top of its team's folders.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="documents.folder",
                verbose_name="in folder",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="path",
            field=models.CharField(
                blank=True, editable=False, max_length=500, verbose_name="path"
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("team", "name"),
                name="documents_folder_unique_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "name"),
                name="documents_folder_unique_name_in_parent",
            ),
        ),
        migrations.RunPython(fill, migrations.RunPython.noop),
    ]
