# Generated by Django 5.2.17 on 2026-09-26 17:26

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "verdict",
                    models.TextField(
                        blank=True, default="", verbose_name="verdict"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
                "permissions": [
                    ("accept_manuscript", "Can accept a manuscript")
                ],
            },
        ),
    ]
