# Generated by Django 5.2.17 on 2026-09-27 11:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_manuscript"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "scan",
                    models.FileField(
                        blank=True,
                        upload_to="scans/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "archive",
                    models.FileField(blank=True, upload_to="archives/"),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="testapp.author",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="DocumentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="testapp.document",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
