# Generated by Django 5.2.17 on 2026-10-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_teams", "0001_initial"),
        ("testapp", "0003_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Binder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "attachment",
                    models.FileField(blank=True, upload_to="binders/"),
                ),
                (
                    "attachment_name",
                    models.CharField(blank=True, max_length=200),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="binders",
                        to="generic_teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="BinderSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "binder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="testapp.binder",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="SharedNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_notes",
                        to="generic_teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
